backend:
  name: github
  repo: mauricefasseu/website_band
  branch: main

media_folder: "images/uploads" # Speicherort f√ºr Medien
public_folder: "/images/uploads"

collections:
  - name: "band"
    label: "Bandmitglieder"
    folder: "content/band"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Rolle", name: "role", widget: "string" }
      - { label: "Bild", name: "image", widget: "image" }
      - { label: "Biografie", name: "bio", widget: "markdown" }
